### ISSUE TITLE
System.ArgumentOutOfRangeException: CommentCop.Misc.MR8000XMLCommentMustBePreceededByBlankLine

### ISSUE THREAD

**Issue by WizX20** [mreu/CommentCop#1]
Example of the class in question:

`
namespace Project.Foundation.SitecoreExtensions.Abstractions
{
  using System.Collections.Generic;
  using System.Linq;
  using Sitecore.Data;
  using Sitecore.Data.Items;

  /// <summary>
    /// Represents a wrapper around an actual Sitecore data <see cref="TemplateItem"/>.
    /// </summary>
    public class SitecoreTemplateItem : /*CustomItemBase,*/ ISitecoreTemplateItem
    {
        private readonly TemplateItem _item;

        /// <summary>
        /// for mocking purposes only
        /// </summary>
        public SitecoreTemplateItem()
        {
            // for mocking purposes only
        }
        /// <summary>
        /// Creates a wrapper around an actual Sitecore data <see cref="TemplateItem"/>.
        /// </summary>
        public SitecoreTemplateItem(TemplateItem templateItem)// : base(templateItem.InnerItem)
        {
            this._item = templateItem;
        }

        /// <summary>
        /// Gets a list of base templates.
        /// </summary>
        public virtual IEnumerable<SitecoreTemplateItem> BaseTemplates
        {
            get { return this._item.BaseTemplates.Select(ToSitecoreTemplateItem); }
        }
`

Exception:
`
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'CommentCop.Misc.MR8000XMLCommentMustBePreceededByBlankLine' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Specified argument was out of the range of valid values.
Parameter name: index'.	Onvz.Foundation.SitecoreExtensions		1	Active	Analyzer 'CommentCop.Misc.MR8000XMLCommentMustBePreceededByBlankLine' threw the following exception:
'Exception occurred with following context:
Compilation: Onvz.Foundation.SitecoreExtensions
SyntaxTree: C:\Projects\OSP\src\foundation\SitecoreExtensions\code\Abstractions\SitecoreTemplateItem.cs
SyntaxNode:  <summary>
  Creates a wrapper around an actual Sitecore data  ... [DocumentationCommentTriviaSyntax]@[641..767) (21,11)-(24,0)

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at Microsoft.CodeAnalysis.SyntaxTriviaList.get_Item(Int32 index)
   at CommentCop.Misc.MR8000XMLCommentMustBePreceededByBlankLine.Check(SyntaxNodeAnalysisContext syntaxNodeAnalysisContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
`

**Comment by WizX20** [comment]
Sorry for the formatting, the markdown code tags fail here.

**Comment by Smurf-IV** [comment]
+1 in Vis 2017 Pro

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	AD0001	Analyzer 'CommentCop.Misc.MR8000XMLCommentMustBePreceededByBlankLine' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Specified argument was out of the range of valid values.
Parameter name: index'.	Alarms.Interface		1	Active
```

**Comment by mreu** [comment]
I try to reproduce the bug the last days but with no success. Can you send me the files that causes the bug and write what you was doing (i.e. inserting a new line typing some text...)?. You can drag and drop the files into the input field when entering a message. I was testing with VS2017
Thanks

**Comment by WizX20** [comment]
`Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'CommentCop.Misc.MR8000XMLCommentMustBePreceededByBlankLine' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Specified argument was out of the range of valid values.
Parameter name: index'.	Onvz.Foundation.Theming		1	Active	Analyzer 'CommentCop.Misc.MR8000XMLCommentMustBePreceededByBlankLine' threw the following exception:
'Exception occurred with following context:
Compilation: MyCode.Foundation.Theming
SyntaxTree: C:\Projects\Project\src\Foundation\Theming\code\Extensions\CarouselOptions.cs
SyntaxNode:  <summary>
  Gets or sets a value indicating whether  ... [DocumentationCommentTriviaSyntax]@[279..361) (11,7)-(14,0)

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at Microsoft.CodeAnalysis.SyntaxTriviaList.get_Item(Int32 index)
   at CommentCop.Misc.MR8000XMLCommentMustBePreceededByBlankLine.Check(SyntaxNodeAnalysisContext syntaxNodeAnalysisContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
`

[CarouselOptions.cs.txt](https://github.com/mreu/CommentCop/files/1084428/CarouselOptions.cs.txt)

I was adding comment all over the place, I have about 500 warnings about missing comments now.
